/// Generate `~/.claude/CLAUDE.md` — Claude Code's awareness of installed tools.
///
/// After every `dfiles apply`, dfiles scans the Claude Code directories for
/// installed skills and commands and writes a structured CLAUDE.md so Claude Code
/// knows what capabilities are available.
///
/// Skills are read from `{claude_dir}/skills/*/SKILL.md` YAML frontmatter:
///
/// ```markdown
/// ---
/// name: office-hours
/// description: "YC Office Hours partner — brainstorm and design"
/// ---
/// ```
///
/// Commands are read from `{claude_dir}/commands/**/*.md` (same format) or top-level
/// `.md` files.
use anyhow::Result;
use std::path::Path;

struct ItemMeta {
    name: String,
    description: String,
}

/// Scan installed skills and commands and write `{claude_dir}/CLAUDE.md`.
pub fn generate(claude_dir: &Path, profile: &str) -> Result<()> {
    let skills = scan_skills(&claude_dir.join("skills"));
    let commands = scan_commands(&claude_dir.join("commands"));

    let now = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let mut out = format!(
        "# Claude Code Environment\nGenerated by dfiles on {} (profile: {})\n",
        now, profile
    );

    if !skills.is_empty() {
        out.push_str("\n## Installed Skills\n");
        for (name, desc) in &skills {
            out.push_str(&format!("- /{}: {}\n", name, desc));
        }
    }

    if !commands.is_empty() {
        out.push_str("\n## Slash Commands\n");
        for (name, desc) in &commands {
            out.push_str(&format!("- /{}: {}\n", name, desc));
        }
    }

    let path = claude_dir.join("CLAUDE.md");
    std::fs::create_dir_all(claude_dir)?;
    std::fs::write(&path, out)
        .map_err(|e| anyhow::anyhow!("Cannot write {}: {}", path.display(), e))
}

/// Scan `skills_dir` for subdirectories containing a `SKILL.md` manifest.
///
/// Returns `(name, description)` pairs sorted alphabetically.
pub fn scan_skills(skills_dir: &Path) -> Vec<(String, String)> {
    let mut items = Vec::new();
    let entries = match std::fs::read_dir(skills_dir) {
        Ok(e) => e,
        Err(_) => return items,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let skill_md = path.join("SKILL.md");
        if skill_md.exists() {
            if let Some(meta) = read_frontmatter(&skill_md) {
                items.push((meta.name, meta.description));
                continue;
            }
        }
        // Fallback: use the directory name when no SKILL.md or no frontmatter.
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        items.push((name, "(no description)".into()));
    }
    items.sort_by(|a, b| a.0.cmp(&b.0));
    items
}

/// Scan `commands_dir` for `.md` files (top-level or in subdirectories).
///
/// Returns `(name, description)` pairs sorted alphabetically.
pub fn scan_commands(commands_dir: &Path) -> Vec<(String, String)> {
    let mut items = Vec::new();
    let entries = match std::fs::read_dir(commands_dir) {
        Ok(e) => e,
        Err(_) => return items,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Subdirectory of commands: look for a COMMAND.md or first .md file.
            let cmd_md = path.join("COMMAND.md");
            if cmd_md.exists() {
                if let Some(meta) = read_frontmatter(&cmd_md) {
                    items.push((meta.name, meta.description));
                    continue;
                }
            }
            let name = path
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            items.push((name, "(no description)".into()));
        } else if path.extension().is_some_and(|e| e == "md") {
            // Top-level .md file.
            if let Some(meta) = read_frontmatter(&path) {
                items.push((meta.name, meta.description));
            } else {
                let name = path
                    .file_stem()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .into_owned();
                items.push((name, "(no description)".into()));
            }
        }
    }
    items.sort_by(|a, b| a.0.cmp(&b.0));
    items
}

/// Parse YAML frontmatter from a Markdown file to extract `name` and `description`.
///
/// ```markdown
/// ---
/// name: my-skill
/// description: "Does the thing"
/// ---
/// ```
fn read_frontmatter(path: &Path) -> Option<ItemMeta> {
    let text = std::fs::read_to_string(path).ok()?;
    // Frontmatter must start on the very first line.
    let after_open = text.strip_prefix("---\n")?;
    let (block, _) = after_open.split_once("\n---")?;

    let mut name = None;
    let mut description = None;
    for line in block.lines() {
        if let Some(v) = line.strip_prefix("name:") {
            name = Some(v.trim().trim_matches('"').to_string());
        } else if let Some(v) = line.strip_prefix("description:") {
            description = Some(v.trim().trim_matches('"').to_string());
        }
    }

    Some(ItemMeta {
        name: name?,
        description: description.unwrap_or_else(|| "(no description)".into()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_skill(skills_dir: &Path, skill_name: &str, description: &str) {
        let skill_dir = skills_dir.join(skill_name);
        std::fs::create_dir_all(&skill_dir).unwrap();
        std::fs::write(
            skill_dir.join("SKILL.md"),
            format!(
                "---\nname: {}\ndescription: \"{}\"\n---\n\n# Skill content\n",
                skill_name, description
            ),
        )
        .unwrap();
    }

    #[test]
    fn generates_claude_md_with_skills() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_dir).unwrap();
        make_skill(&skills_dir, "office-hours", "YC Office Hours partner");
        make_skill(&skills_dir, "ship", "Release engineer");

        generate(tmp.path(), "work").unwrap();

        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains("## Installed Skills"), "Skills section missing");
        assert!(content.contains("/office-hours: YC Office Hours partner"));
        assert!(content.contains("/ship: Release engineer"));
        assert!(content.contains("profile: work"));
    }

    #[test]
    fn generates_claude_md_with_no_skills() {
        let tmp = TempDir::new().unwrap();
        generate(tmp.path(), "default").unwrap();

        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains("Generated by dfiles"));
        assert!(!content.contains("## Installed Skills"));
    }

    #[test]
    fn skills_sorted_alphabetically() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_dir).unwrap();
        make_skill(&skills_dir, "zzz-skill", "Last");
        make_skill(&skills_dir, "aaa-skill", "First");

        generate(tmp.path(), "default").unwrap();
        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        let aaa_pos = content.find("/aaa-skill").unwrap();
        let zzz_pos = content.find("/zzz-skill").unwrap();
        assert!(aaa_pos < zzz_pos, "skills should be sorted alphabetically");
    }

    #[test]
    fn reads_name_and_description_from_frontmatter() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("SKILL.md");
        std::fs::write(
            &file,
            "---\nname: my-skill\ndescription: \"Does the thing\"\n---\n",
        )
        .unwrap();
        let meta = read_frontmatter(&file).unwrap();
        assert_eq!(meta.name, "my-skill");
        assert_eq!(meta.description, "Does the thing");
    }

    #[test]
    fn returns_none_for_missing_frontmatter() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("SKILL.md");
        std::fs::write(&file, "# No frontmatter here\n").unwrap();
        assert!(read_frontmatter(&file).is_none());
    }

    #[test]
    fn returns_none_for_frontmatter_without_name() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("SKILL.md");
        std::fs::write(&file, "---\ndescription: \"No name\"\n---\n").unwrap();
        assert!(read_frontmatter(&file).is_none());
    }

    #[test]
    fn fallback_name_when_no_skill_md() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(skills_dir.join("my-tool")).unwrap();

        generate(tmp.path(), "default").unwrap();
        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains("/my-tool: (no description)"));
    }
}
