/// Generate `~/.claude/CLAUDE.md` — Claude Code's awareness of installed tools.
///
/// After every `haven apply`, haven scans the Claude Code directories for
/// installed skills and commands and writes a structured CLAUDE.md so Claude Code
/// knows what capabilities are available.
///
/// Haven's section is delimited by HTML comment markers so user content outside
/// the markers is preserved across runs:
///
/// ```markdown
/// <!-- haven managed start -->
/// # Claude Code Environment
/// ...
/// <!-- haven managed end -->
/// ```
///
/// If the markers are absent, haven appends its section at the end of the file.
///
/// Skills are read from `{claude_dir}/skills/*/SKILL.md` YAML frontmatter:
///
/// ```markdown
/// ---
/// name: office-hours
/// description: "YC Office Hours partner — brainstorm and design"
/// ---
/// ```
///
/// Commands are read from `{claude_dir}/commands/**/*.md` (same format) or top-level
/// `.md` files.
use anyhow::Result;
use std::path::Path;

pub const MARKER_START: &str = "<!-- haven managed start -->";
pub const MARKER_END: &str = "<!-- haven managed end -->";

struct ItemMeta {
    name: String,
    description: String,
}

/// Build the `<!-- haven managed -->` block that `generate` would write.
///
/// The block includes the header, installed skills listing, commands listing,
/// and per-skill snippets from the repo.  The `Generated by haven on <date>`
/// line is included so the output matches exactly what `generate` writes.
///
/// For staleness comparison, use [`is_claude_md_stale`] instead, which
/// normalises the date line out of both sides.
fn build_managed_block(claude_dir: &Path, repo_root: Option<&Path>, profile: &str) -> String {
    let skills = scan_skills(&claude_dir.join("skills"));
    let commands = scan_commands(&claude_dir.join("commands"));

    let now = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let mut haven_content = format!(
        "# Claude Code Environment\nGenerated by haven on {} (profile: {})\n",
        now, profile
    );

    // Skill snippets come first so Claude Code reads them before the index.
    if let Some(rr) = repo_root {
        for (skill_name, _) in &skills {
            let snippet = read_skill_snippet(rr, skill_name);
            if !snippet.is_empty() {
                haven_content.push_str(&format!(
                    "\n<!-- skill: {} -->\n{}\n<!-- /skill: {} -->\n",
                    skill_name,
                    snippet.trim_end(),
                    skill_name,
                ));
            }
        }
    }

    if !skills.is_empty() {
        haven_content.push_str("\n## Installed Skills\n");
        for (name, desc) in &skills {
            haven_content.push_str(&format!("- /{}: {}\n", name, desc));
        }
    }

    if !commands.is_empty() {
        haven_content.push_str("\n## Slash Commands\n");
        for (name, desc) in &commands {
            haven_content.push_str(&format!("- /{}: {}\n", name, desc));
        }
    }

    format!("{}\n{}{}\n", MARKER_START, haven_content, MARKER_END)
}

/// Return `true` if the haven-managed section in `{claude_dir}/CLAUDE.md`
/// does not match what `generate` would write today.
///
/// The `Generated by haven on <date>` line is ignored so that a date-only
/// difference doesn't trigger a false positive.  Returns `false` when the
/// file doesn't exist or has no haven section (not stale, just absent).
pub fn is_claude_md_stale(claude_dir: &Path, repo_root: Option<&Path>, profile: &str) -> bool {
    let path = claude_dir.join("CLAUDE.md");
    let Ok(current) = std::fs::read_to_string(&path) else {
        return false;
    };

    // Extract the current haven block from the file.
    let Some(s) = current.find(MARKER_START) else {
        return false; // no section yet — handled by generate on next apply
    };
    let Some(e_rel) = current[s..].find(MARKER_END) else {
        return false;
    };
    let current_block = &current[s..s + e_rel + MARKER_END.len()];

    let expected_block = build_managed_block(claude_dir, repo_root, profile);

    strip_date_line(&expected_block) != strip_date_line(current_block)
}

/// Remove the `Generated by haven on …` line so date-only changes don't
/// count as drift.
fn strip_date_line(text: &str) -> String {
    text.lines()
        .filter(|l| !l.starts_with("Generated by haven on "))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Scan installed skills, commands, and skill snippets, then write
/// `{claude_dir}/CLAUDE.md`.
///
/// Preserves any user content outside haven's managed section markers.
///
/// When `repo_root` is provided, skill snippets are gathered from
/// `{repo_root}/ai/skills/{name}/all.md` and
/// `{repo_root}/ai/skills/{name}/claude-code.md` for each installed skill
/// and appended to the managed section.
pub fn generate(claude_dir: &Path, repo_root: Option<&Path>, profile: &str) -> Result<()> {
    let managed_block = build_managed_block(claude_dir, repo_root, profile);

    let path = claude_dir.join("CLAUDE.md");
    std::fs::create_dir_all(claude_dir)?;

    let existing = std::fs::read_to_string(&path).unwrap_or_default();

    let output = if let Some(start) = existing.find(MARKER_START) {
        if let Some(end_rel) = existing[start..].find(MARKER_END) {
            let end = start + end_rel + MARKER_END.len();
            // Consume one trailing newline after the end marker if present.
            let end = if existing.as_bytes().get(end) == Some(&b'\n') {
                end + 1
            } else {
                end
            };
            format!("{}{}{}", &existing[..start], managed_block, &existing[end..])
        } else {
            // Malformed: start marker with no end — replace from start to EOF.
            format!("{}{}", &existing[..start], managed_block)
        }
    } else if existing.is_empty() {
        managed_block
    } else {
        // File has user content but no haven markers — append haven section.
        let sep = if existing.ends_with('\n') { "\n" } else { "\n\n" };
        format!("{}{}{}", existing, sep, managed_block)
    };

    std::fs::write(&path, output)
        .map_err(|e| anyhow::anyhow!("Cannot write {}: {}", path.display(), e))
}

/// Strip the haven-managed section from `text`, returning only user content.
///
/// Removes the block between `<!-- haven managed start -->` and
/// `<!-- haven managed end -->` (inclusive), along with the blank-line
/// separator that precedes it.  Used by drift checks and `haven add` to
/// compare or store only user-authored content.
pub fn strip_haven_section(text: &str) -> String {
    let Some(s) = text.find(MARKER_START) else {
        return text.to_string();
    };
    let Some(e_rel) = text[s..].find(MARKER_END) else {
        return text.to_string();
    };
    let e = s + e_rel + MARKER_END.len();
    // Consume trailing newline after end marker.
    let e = if text.as_bytes().get(e) == Some(&b'\n') { e + 1 } else { e };
    // Trim one leading newline before the start marker (the blank-line separator).
    let s = if s > 0 && text.as_bytes().get(s - 1) == Some(&b'\n') { s - 1 } else { s };
    format!("{}{}", &text[..s], &text[e..])
}

/// Read the combined snippet for a skill on the claude-code platform.
///
/// Concatenates `all.md` (cross-platform) followed by `claude-code.md`
/// (platform-specific), separated by a blank line.  Returns an empty string
/// if neither file has non-whitespace content.
fn read_skill_snippet(repo_root: &Path, skill_name: &str) -> String {
    let skill_dir = repo_root.join("ai").join("skills").join(skill_name);
    let all = read_nonempty_file(&skill_dir.join("all.md"));
    let specific = read_nonempty_file(&skill_dir.join("claude-code.md"));
    match (all, specific) {
        (Some(a), Some(s)) => format!("{}\n\n{}", a.trim_end(), s.trim_end()),
        (Some(a), None) => a.trim_end().to_string(),
        (None, Some(s)) => s.trim_end().to_string(),
        (None, None) => String::new(),
    }
}

fn read_nonempty_file(path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(path).ok()?;
    if content.trim().is_empty() { None } else { Some(content) }
}

/// Scan `skills_dir` for subdirectories containing a `SKILL.md` manifest.
///
/// Returns `(name, description)` pairs sorted alphabetically.
pub fn scan_skills(skills_dir: &Path) -> Vec<(String, String)> {
    let mut items = Vec::new();
    let entries = match std::fs::read_dir(skills_dir) {
        Ok(e) => e,
        Err(_) => return items,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let skill_md = path.join("SKILL.md");
        if skill_md.exists() {
            if let Some(meta) = read_frontmatter(&skill_md) {
                items.push((meta.name, meta.description));
                continue;
            }
        }
        // Fallback: use the directory name when no SKILL.md or no frontmatter.
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        items.push((name, "(no description)".into()));
    }
    items.sort_by(|a, b| a.0.cmp(&b.0));
    items
}

/// Scan `commands_dir` for `.md` files (top-level or in subdirectories).
///
/// Returns `(name, description)` pairs sorted alphabetically.
pub fn scan_commands(commands_dir: &Path) -> Vec<(String, String)> {
    let mut items = Vec::new();
    let entries = match std::fs::read_dir(commands_dir) {
        Ok(e) => e,
        Err(_) => return items,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Subdirectory of commands: look for a COMMAND.md or first .md file.
            let cmd_md = path.join("COMMAND.md");
            if cmd_md.exists() {
                if let Some(meta) = read_frontmatter(&cmd_md) {
                    items.push((meta.name, meta.description));
                    continue;
                }
            }
            let name = path
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            items.push((name, "(no description)".into()));
        } else if path.extension().is_some_and(|e| e == "md") {
            // Top-level .md file.
            if let Some(meta) = read_frontmatter(&path) {
                items.push((meta.name, meta.description));
            } else {
                let name = path
                    .file_stem()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .into_owned();
                items.push((name, "(no description)".into()));
            }
        }
    }
    items.sort_by(|a, b| a.0.cmp(&b.0));
    items
}

/// Parse YAML frontmatter from a Markdown file to extract `name` and `description`.
///
/// ```markdown
/// ---
/// name: my-skill
/// description: "Does the thing"
/// ---
/// ```
fn read_frontmatter(path: &Path) -> Option<ItemMeta> {
    let text = std::fs::read_to_string(path).ok()?;
    // Frontmatter must start on the very first line.
    let after_open = text.strip_prefix("---\n")?;
    let (block, _) = after_open.split_once("\n---")?;

    let mut name = None;
    let mut description = None;
    for line in block.lines() {
        if let Some(v) = line.strip_prefix("name:") {
            name = Some(v.trim().trim_matches('"').to_string());
        } else if let Some(v) = line.strip_prefix("description:") {
            description = Some(v.trim().trim_matches('"').to_string());
        }
    }

    Some(ItemMeta {
        name: name?,
        description: description.unwrap_or_else(|| "(no description)".into()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_skill(skills_dir: &Path, skill_name: &str, description: &str) {
        let skill_dir = skills_dir.join(skill_name);
        std::fs::create_dir_all(&skill_dir).unwrap();
        std::fs::write(
            skill_dir.join("SKILL.md"),
            format!(
                "---\nname: {}\ndescription: \"{}\"\n---\n\n# Skill content\n",
                skill_name, description
            ),
        )
        .unwrap();
    }

    #[test]
    fn generates_claude_md_with_skills() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_dir).unwrap();
        make_skill(&skills_dir, "office-hours", "YC Office Hours partner");
        make_skill(&skills_dir, "ship", "Release engineer");

        generate(tmp.path(), None, "work").unwrap();

        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains(MARKER_START), "start marker missing");
        assert!(content.contains(MARKER_END), "end marker missing");
        assert!(content.contains("## Installed Skills"), "Skills section missing");
        assert!(content.contains("/office-hours: YC Office Hours partner"));
        assert!(content.contains("/ship: Release engineer"));
        assert!(content.contains("profile: work"));
    }

    #[test]
    fn generates_claude_md_with_no_skills() {
        let tmp = TempDir::new().unwrap();
        generate(tmp.path(), None, "default").unwrap();

        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains(MARKER_START));
        assert!(content.contains(MARKER_END));
        assert!(content.contains("Generated by haven"));
        assert!(!content.contains("## Installed Skills"));
    }

    #[test]
    fn skills_sorted_alphabetically() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_dir).unwrap();
        make_skill(&skills_dir, "zzz-skill", "Last");
        make_skill(&skills_dir, "aaa-skill", "First");

        generate(tmp.path(), None, "default").unwrap();
        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        let aaa_pos = content.find("/aaa-skill").unwrap();
        let zzz_pos = content.find("/zzz-skill").unwrap();
        assert!(aaa_pos < zzz_pos, "skills should be sorted alphabetically");
    }

    #[test]
    fn preserves_user_content_when_markers_present() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("CLAUDE.md");
        std::fs::write(
            &path,
            format!(
                "# My custom notes\n\nSome user content.\n\n{}\n# Claude Code Environment\nGenerated by haven on 2000-01-01 (profile: old)\n{}\n",
                MARKER_START, MARKER_END
            ),
        )
        .unwrap();

        generate(tmp.path(), None, "new").unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("# My custom notes"), "user content lost");
        assert!(content.contains("Some user content."), "user content lost");
        assert!(content.contains("profile: new"), "haven section not updated");
        // Only one copy of each marker.
        assert_eq!(content.matches(MARKER_START).count(), 1);
        assert_eq!(content.matches(MARKER_END).count(), 1);
    }

    #[test]
    fn appends_haven_section_when_no_markers() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("CLAUDE.md");
        std::fs::write(&path, "# My existing content\n\nUser notes here.\n").unwrap();

        generate(tmp.path(), None, "default").unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("# My existing content"), "user content lost");
        assert!(content.contains("User notes here."), "user content lost");
        assert!(content.contains(MARKER_START), "start marker missing");
        assert!(content.contains(MARKER_END), "end marker missing");
        assert!(content.contains("Generated by haven"));
        // User content comes before haven section.
        let user_pos = content.find("# My existing content").unwrap();
        let marker_pos = content.find(MARKER_START).unwrap();
        assert!(user_pos < marker_pos, "user content should precede haven section");
    }

    #[test]
    fn second_apply_does_not_duplicate_content() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_dir).unwrap();
        make_skill(&skills_dir, "ship", "Release engineer");

        generate(tmp.path(), None, "default").unwrap();
        generate(tmp.path(), None, "default").unwrap();

        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert_eq!(content.matches(MARKER_START).count(), 1);
        assert_eq!(content.matches(MARKER_END).count(), 1);
        assert_eq!(content.matches("/ship:").count(), 1);
    }

    #[test]
    fn reads_name_and_description_from_frontmatter() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("SKILL.md");
        std::fs::write(
            &file,
            "---\nname: my-skill\ndescription: \"Does the thing\"\n---\n",
        )
        .unwrap();
        let meta = read_frontmatter(&file).unwrap();
        assert_eq!(meta.name, "my-skill");
        assert_eq!(meta.description, "Does the thing");
    }

    #[test]
    fn returns_none_for_missing_frontmatter() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("SKILL.md");
        std::fs::write(&file, "# No frontmatter here\n").unwrap();
        assert!(read_frontmatter(&file).is_none());
    }

    #[test]
    fn returns_none_for_frontmatter_without_name() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("SKILL.md");
        std::fs::write(&file, "---\ndescription: \"No name\"\n---\n").unwrap();
        assert!(read_frontmatter(&file).is_none());
    }

    // ── is_claude_md_stale ────────────────────────────────────────────────────

    #[test]
    fn stale_returns_false_when_no_file() {
        let tmp = TempDir::new().unwrap();
        assert!(!is_claude_md_stale(tmp.path(), None, "default"));
    }

    #[test]
    fn stale_returns_false_when_no_haven_section() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("CLAUDE.md"), "# User content only\n").unwrap();
        assert!(!is_claude_md_stale(tmp.path(), None, "default"));
    }

    #[test]
    fn stale_returns_false_when_up_to_date() {
        let tmp = TempDir::new().unwrap();
        make_skill(&tmp.path().join("skills"), "my-skill", "Does the thing");
        generate(tmp.path(), None, "default").unwrap();
        // Immediately after generate, should be clean.
        assert!(!is_claude_md_stale(tmp.path(), None, "default"));
    }

    #[test]
    fn stale_returns_true_when_skill_added_after_generate() {
        let tmp = TempDir::new().unwrap();
        generate(tmp.path(), None, "default").unwrap();
        // Install a new skill AFTER generate ran — now it's stale.
        make_skill(&tmp.path().join("skills"), "new-skill", "Brand new");
        assert!(is_claude_md_stale(tmp.path(), None, "default"));
    }

    #[test]
    fn stale_returns_true_when_snippet_changed() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        make_skill(&skills_dir, "my-skill", "Does the thing");
        // Write a snippet file in the repo.
        let snippet_dir = tmp.path().join("ai").join("skills").join("my-skill");
        std::fs::create_dir_all(&snippet_dir).unwrap();
        std::fs::write(snippet_dir.join("all.md"), "Original instructions.\n").unwrap();

        generate(tmp.path(), Some(tmp.path()), "default").unwrap();
        assert!(!is_claude_md_stale(tmp.path(), Some(tmp.path()), "default"));

        // Edit the snippet — should now be stale.
        std::fs::write(snippet_dir.join("all.md"), "Updated instructions.\n").unwrap();
        assert!(is_claude_md_stale(tmp.path(), Some(tmp.path()), "default"));
    }

    #[test]
    fn stale_ignores_date_line() {
        let tmp = TempDir::new().unwrap();
        generate(tmp.path(), None, "default").unwrap();
        // Overwrite just the date in the haven section — should still be clean.
        let path = tmp.path().join("CLAUDE.md");
        let content = std::fs::read_to_string(&path).unwrap();
        let mangled = content.replace(
            "Generated by haven on ",
            "Generated by haven on 1999-01-01 (profile: zzz)\nGenerated by haven on ",
        );
        // Restore a plausible-but-different date line only.
        let patched = content.replace(
            &format!(
                "Generated by haven on {}",
                chrono::Utc::now().format("%Y-%m-%d")
            ),
            "Generated by haven on 2000-01-01",
        );
        std::fs::write(&path, &patched).unwrap();
        assert!(!is_claude_md_stale(tmp.path(), None, "default"), "{}", mangled);
    }

    #[test]
    fn fallback_name_when_no_skill_md() {
        let tmp = TempDir::new().unwrap();
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(skills_dir.join("my-tool")).unwrap();

        generate(tmp.path(), None, "default").unwrap();
        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains("/my-tool: (no description)"));
    }
}
